
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL_UNPOOLED='your_database_url_here'
      - HUGGINGFACE_API_TOKEN='your_token_here'
    volumes:
      - ./backend:/app
      - /app/venv
    restart: unless-stopped
    networks:
      - splitwise-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - splitwise-network

networks:
  splitwise-network:
    driver: bridge 